<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)\Build_Scripts\Base_WinExe.props" />

	<!--Project Info-->
	<PropertyGroup>
		<ApplicationIcon>$(SolutionDir)\Resources\SourcePlus_Icon.ico</ApplicationIcon>
		<Description>Source+ Editor</Description>
	</PropertyGroup>

	<!--NuGet Packages-->
	<ItemGroup>
		<PackageReference Include="ImGui.NET" Version="1.91.6.1" />
		<PackageReference Include="Raylib-cs" Version="7.0.2" />
		<PackageReference Include="rlImGui-cs" Version="3.2.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(SolutionDir)\Resources\SourcePlus_Icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>Content\ApplicationIcon.png</Link>
		</None>
	</ItemGroup>
</Project>
