<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)\Build\Base_WinExe.props" />

	<PropertyGroup>
		<!--ooooooooooo vewy scawy-->
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<!--Project Info-->
	<PropertyGroup>
		<ApplicationIcon>$(SolutionDir)\Resources\SourcePlus_Icon.ico</ApplicationIcon>
		<Description>Source+ Editor</Description>
	</PropertyGroup>

	<!--NuGet Packages-->
	<ItemGroup>
		<PackageReference Include="ImGui.NET" Version="1.91.6.1" />
		<PackageReference Include="Raylib-cs" Version="7.0.2" />
		<PackageReference Include="rlImGui-cs" Version="3.2.0" />
		<PackageReference Include="ValveKeyValue" Version="0.20.0.417" />
	</ItemGroup>

	<!--Copy Source+ Icon & Logo to Build-->
	<ItemGroup>
		<Content Include="$(SolutionDir)\Resources\SourcePlus_Icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>..\resources\sourceplus_icon.png</Link>
			<Visible>false</Visible>
		</Content>
		<Content Include="$(SolutionDir)\Resources\SourcePlus_Logo.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>..\resources\sourceplus_logo.png</Link>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>

	<!--Copy Default ImGui configuration to Build-->
	<ItemGroup>
		<Content Include="$(SolutionDir)\Resources\imgui.ini">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>..\resources\imgui.ini</Link>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>
</Project>
