<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)\Build_Scripts\Base_WinExe.props" />

	<!--Project Info-->
	<PropertyGroup>
		<ApplicationIcon>$(SolutionDir)\Resources\SourcePlus_Icon.ico</ApplicationIcon>
		<Description>Source+ Editor</Description>
	</PropertyGroup>

	<!--NuGet Packages-->
	<ItemGroup>
		<PackageReference Include="Raylib-cs" Version="7.0.2" />
	</ItemGroup>
</Project>
