<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(MSBuildThisFileDirectory)\..\Build\Base_Dll.props" />
	
	<!--Project Info-->
	<PropertyGroup>
		<RootNamespace>SourcePlus</RootNamespace>
	</PropertyGroup>

	<!--Remove Common project reference to prevent cyclic dependencies-->
	<ItemGroup>
		<ProjectReference Remove="$(MSBuildThisFileDirectory)\..\Common\Common.csproj" />
	</ItemGroup>
</Project>
